### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by ghost** [supercom32/dosktop#6]
After going through the repository, I could not find an examples folder, could you provide a small getting started example? Thanks for this awesome project.

**Comment by jimmy201602** [comment]
Can i get the examples?

**Comment by supercom32** [comment]
Hi there,

Thanks for the kind message. I am currently working on the package Consolizer which will be an upgrade to Dosktop, but it is not ready yet. However, Dosktop is still in a usable state.  While I don't have any specific examples for it, here is some sample code to get you started. The methods are well documented so hopefully by snooping around with your IDE, you can figure out what you need.

```
func main() {
        width := 80
	height := 25
	FOREGROUND_LAYER := "ForegroundLayer"
	BACKGROUND_LAYER := "BackgroundLayer"
	WINDOW_LAYER := "WindowLayer"
	dosktop.InitializeTerminal(width, height)
	defer dosktop.RestoreTerminalSettings()
	dosktop.AddLayer(FOREGROUND_LAYER, 0, 0,width, height, 1, "")
	dosktop.AddLayer(BACKGROUND_LAYER, 0, 0,width, height, 0, "")
	dosktop.AddLayer(WINDOW_LAYER, 0, 0,width, height, 2, "")
	dosktop.ColorLayer(BACKGROUND_LAYER, 4, 7)
	dosktop.FillLayer(BACKGROUND_LAYER, ("░"))
	dosktop.DrawBar(BACKGROUND_LAYER,0,0, 80, " ")
	dosktop.DrawBar(BACKGROUND_LAYER,0,24, 80, " ")
	dosktop.LocateLayer(BACKGROUND_LAYER, 0, 0)
	dosktop.ColorLayer(BACKGROUND_LAYER, 0, 7)
	dosktop.PrintLayer(BACKGROUND_LAYER, " Example Title Bar"
	dosktop.UpdateDisplay()
	for {
		input := dosktop.Inkey()
		if input == "q" {
			os.Exit(0)
		}
	}
}

**Comment by jimmy201602** [comment]
Thanks a lot.

**Comment by Isopropyl-lab** [comment]
I would also like to see more examples.
